export const FETCH_EVENTS_REQUEST = "FETCH_EVENTS_REQUEST";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_FAILURE = "FETCH_EVENTS_FAILURE";
export const SET_CURRENT_TIME = "SET_CURRENT_TIME";
export const UPDATE_ACTIVE_EVENTS = "UPDATE_ACTIVE_EVENTS";

export const TOGGLE_PLAYING = "TOGGLE_PLAYING";
export const SET_CURRENT_EVENT = "SET_CURRENT_EVENT";
export const SHOW_RECTANGLE = "SHOW_RECTANGLE";
export const HIDE_RECTANGLE = "HIDE_RECTANGLE";
