export const FETCH_EVENTS_REQUEST = "FETCH_EVENTS_REQUEST";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_FAILURE = "FETCH_EVENTS_FAILURE";
export const SET_CURRENT_TIME = "SET_CURRENT_TIME";
export const SET_CURRENT_EVENT = "SET_CURRENT_EVENT";
export const SET_ACTIVE_EVENTS = "SET_ACTIVE_EVENTS";
